#ifndef GLOBALS_H
#define GLOBALS_H

#define XDRILLER_VERSION_MAJOR 0
#define XDRILLER_VERSION_MINOR 3
#define XDRILLER_VERSION_PATCH 0

#define XDRILLER_VERSION    ((XDRILLER_VERSION_MAJOR << 16) | (XDRILLER_VERSION_MINOR << 8) | XDRILLER_VERSION_PATCH)

#define XDRILLER_VERSION_STRING "0.3"

#define XDRILLER_DEBUG 1

#endif
